
on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      # - name: 'testing github action'
      #   run: pwd

      # - name: 'testing printing'
      #   run: echo omar

      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username omar2307 --password dckr_pat_ue_V7G2sgQgmAam3jKenU4iLd6I


