
on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: 'testing github action'
        run: pwd

      - name: 'testing printing'
        run: echo omar


      - uses: actions/checkout@v3

      - name: 'list'
        run: ls


